"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const performExploration_1 = require("./Functions/performExploration");
const StartCombat_1 = require("./Functions/StartCombat");
const ExplorationShip_1 = require("./Ships/ExplorationShip");
const FighterShip_1 = require("./Ships/FighterShip");
const MultipleShips_1 = require("./Ships/MultipleShips");
const TransportShip_1 = require("./Ships/TransportShip");
const Planets_1 = require("./Support/Planets");
const fighter = new FighterShip_1.Fighter('Nave atacante', 100);
const transportShip = new TransportShip_1.TransportShip('Nave transportadora');
const explorationShip = new ExplorationShip_1.ExplorationShip('Classe exploradora');
const multiPurposeShip = new MultipleShips_1.MultipleShip('Nave multipla', 100);
(0, StartCombat_1.startCombat)(multiPurposeShip, explorationShip);
(0, performExploration_1.performExploration)(explorationShip, Planets_1.Planets.EARTH);
const combatShips = [];
const explorationShips = [];
const cargoShips = [];
combatShips.push(fighter);
combatShips.push(multiPurposeShip);
combatShips.push(multiPurposeShip);
explorationShips.push(multiPurposeShip);
cargoShips.push(multiPurposeShip);
